controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
#home:
#    path: /
#    controller: App\Controller\HomeController::index
#
## LOGIN
#login:
#    path: /login
#    controller: App\Controller\AuthController::login
